import {
  FaReact,
  FaNodeJs,
  FaAngular,
  FaJava,
  FaSass,
  FaCss3Alt,
  FaAndroid,
  FaDocker,
} from "react-icons/fa";
import { GrGraphQl, GrMysql } from "react-icons/gr";
import { IoLogoJavascript } from "react-icons/io5";
import {
  SiCypress,
  SiGithubactions,
  SiJest,
  SiMongodb,
  SiNestjs,
  SiNextdotjs,
  SiPrisma,
  SiRedux,
  SiSelenium,
  SiSonarcloud,
  SiSpring,
  SiStyledcomponents,
  SiTypescript,
  SiVtex,
  SiVuedotjs,
  SiWebpack,
} from "react-icons/si";
import { RiFirebaseFill } from "react-icons/ri";
import { t } from "i18next";
export const stacksAndSkills = ({ iconSize = 40 }) => {
  return [
    {
      name: "React",
      icon: <FaReact size={iconSize} color="#fff" />,
      bgColor: "#00D8FF",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.react_description"),
      callForLink: t("stacks_page.react_callForLink"),
    },
    {
      name: "Node JS",
      icon: <FaNodeJs size={iconSize} color="#fff" />,
      bgColor: "#669C4F",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.node_description"),
      callForLink: t("stacks_page.node_callForLink"),
    },
    {
      name: "MySQL",
      icon: <GrMysql size={iconSize} color="#fff" />,
      bgColor: "#004E63",
      projectLink: "",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.mysql_description"),
      callForLink: t("stacks_page.mysql_callForLink"),
    },
    {
      name: "Mongo DB",
      icon: <SiMongodb size={iconSize} color="#fff" />,
      bgColor: "#499D4A",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.mongo_description"),
      callForLink: t("stacks_page.mongo_callForLink"),
    },
    {
      name: "Vue JS",
      icon: <SiVuedotjs size={iconSize} color="#fff" />,
      bgColor: "#41B883",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.vue_description"),
      callForLink: t("stacks_page.vue_callForLink"),
    },
    {
      name: "Angular JS",
      icon: <FaAngular size={iconSize} color="#fff" />,
      bgColor: "#C3002F",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.angular_description"),
      callForLink: t("stacks_page.angular_callForLink"),
    },
    {
      name: "Docker",
      icon: <FaDocker size={iconSize} color="#fff" />,
      bgColor: "#2496ED",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.docker_description"),
      callForLink: t("stacks_page.docker_callForLink"),
    },
    {
      name: "VTEX",
      icon: <SiVtex size={iconSize} color="#fff" />,
      bgColor: "#EC4E6E",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.vtex_description"),
      callForLink: t("stacks_page.vtex_callForLink"),
    },
    {
      name: "SonarCloud",
      icon: <SiSonarcloud size={iconSize} color="#fff" />,
      bgColor: "#F3702A",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.sonarcloud_description"),
      callForLink: t("stacks_page.sonarcloud_callForLink"),
    },
    {
      name: "Nest JS",
      icon: <SiNestjs size={iconSize} color="#fff" />,
      bgColor: "#E0234E",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.nest_description"),
      callForLink: t("stacks_page.nest_callForLink"),
    },
    {
      name: "Android",
      icon: <FaAndroid size={iconSize} color="#fff" />,
      bgColor: "#34A853",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.android_description"),
      callForLink: t("stacks_page.android_callForLink"),
    },
    {
      name: "Spring Boot",
      icon: <SiSpring size={iconSize} color="#fff" />,
      bgColor: "#79AB4D",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.spring_description"),
      callForLink: t("stacks_page.spring_callForLink"),
    },
    {
      name: "CSS",
      icon: <FaCss3Alt size={iconSize} color="#fff" />,
      bgColor: "#1572B6",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.css_description"),
      callForLink: t("stacks_page.css_callForLink"),
    },
    {
      name: "GraphQL",
      icon: <GrGraphQl size={iconSize} color="#fff" />,
      bgColor: "#E535AB",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.graphql_description"),
      callForLink: t("stacks_page.graphql_callForLink"),
    },
    {
      name: "Javascript",
      icon: <IoLogoJavascript size={iconSize} color="#fff" />,
      bgColor: "#D8C01C",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.js_description"),
      callForLink: t("stacks_page.js_callForLink"),
    },
    {
      name: "Github Actions",
      icon: <SiGithubactions size={iconSize} color="#fff" />,
      bgColor: "#272727",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.github_description"),
      callForLink: t("stacks_page.github_callForLink"),
    },
    {
      name: "Firebase",
      icon: <RiFirebaseFill size={iconSize} color="#fff" />,
      bgColor: "#FFA000",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.firebase_description"),
      callForLink: t("stacks_page.firebase_callForLink"),
    },
    {
      name: "Cypress",
      icon: <SiCypress size={iconSize} color="#fff" />,
      bgColor: "#69D99B",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.cy_description"),
      callForLink: t("stacks_page.cy_callForLink"),
    },
    {
      name: "Jest",
      icon: <SiJest size={iconSize} color="#fff" />,
      bgColor: "#99425B",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.jest_description"),
      callForLink: t("stacks_page.jest_callForLink"),
    },
    {
      name: "Next JS",
      icon: <SiNextdotjs size={iconSize} color="#fff" />,
      bgColor: "#272727",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.next_description"),
      callForLink: t("stacks_page.next_callForLink"),
    },
    {
      name: "Java",
      icon: <FaJava size={iconSize} color="#fff" />,
      bgColor: "#5382A1",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.java_description"),
      callForLink: t("stacks_page.java_callForLink"),
    },
    {
      name: "Selenium",
      icon: <SiSelenium size={iconSize} color="#fff" />,
      bgColor: "#2CB134",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.selenium_description"),
      callForLink: t("stacks_page.selenium_callForLink"),
    },
    {
      name: "TypeScript",
      icon: <SiTypescript size={iconSize} color="#fff" />,
      bgColor: "#007ACC",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.typeScript_description"),
      callForLink: t("stacks_page.typeScript_callForLink"),
    },
    {
      name: "Prisma",
      icon: <SiPrisma size={iconSize} color="#fff" />,
      bgColor: "#1B3B52",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.prisma_description"),
      callForLink: t("stacks_page.prisma_callForLink"),
    },
    {
      name: "Redux",
      icon: <SiRedux size={iconSize} color="#fff" />,
      bgColor: "#764ABC",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.redux_description"),
      callForLink: t("stacks_page.redux_callForLink"),
    },
    {
      name: "SASS",
      icon: <FaSass size={iconSize} color="#fff" />,
      bgColor: "#CD6799",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.sass_description"),
      callForLink: t("stacks_page.sass_callForLink"),
    },
    {
      name: "Material UI",
      icon: <FaReact size={iconSize} color="#fff" />,
      bgColor: "#1C7FB6",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.material_description"),
      callForLink: t("stacks_page.material_callForLink"),
    },
    {
      name: "styled",
      icon: <SiStyledcomponents size={iconSize} color="#fff" />,
      bgColor: "#CF5FA6",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.styled_description"),
      callForLink: t("stacks_page.styled_callForLink"),
    },
    {
      name: "Web Pack",
      icon: <SiWebpack size={iconSize} color="#fff" />,
      bgColor: "#1C78C0",
      projectLink: "https://pedrolopes.tech/",
      githubLink: "https://github.com/Pedrolopesh",
      description: t("stacks_page.webpack_description"),
      callForLink: t("stacks_page.webpack_callForLink"),
    },
  ];
};
